### ISSUE TITLE
Add new players to room after game started.

### ISSUE THREAD

**Issue by akasharkxx** [mobiledgex/edge-multiplay-node-server#13]
The project I am working on requires the game to start and allow the addition of new players even after game is started. But currently, I haven't found a way to do this as there are lots of things happening from players joining a room until the GameStarted callback is called.
Explanation  :  The maxPlayers is 10. But the game should start after 2 players are joined and then up to 8 players can join the game and everything should be synced.
I tried to explain the request.

**Comment by ah1053** [comment]
Fixed in 1.3
